version: '3.3'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.5.3"
    ports:
     - "9200:9200"
    environment: 
      "xpack.security.enabled": "false"

  prometheus:
    image: "prom/prometheus"
    ports:
     - "9090:9090"
    volumes:
     - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  elasticsearch_exporter:
    image: "montools/prom-elasticsearch-exporter"
    ports:
     - "9108:9108"
    command: "--es.uri http://elasticsearch:9200/"
