{
 "title": "Axon.ivy Dashboard",
 "tags": [
  "prometheus",
  "Axon.ivy"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{job='jmx'}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Free Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (java_lang_OperatingSystem_FreePhysicalMemorySize{instance=~\"$instance\"} / on(instance) java_lang_OperatingSystem_TotalPhysicalMemorySize{instance=~\"$instance\"} *100)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_TotalPhysicalMemorySize{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (java_lang_OperatingSystem_FreeSwapSpaceSize{instance=~\"$instance\"} / on(instance) java_lang_OperatingSystem_TotalSwapSpaceSize{instance=~\"$instance\"} * 100)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_TotalSwapSpaceSize{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU System Load(1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(java_lang_OperatingSystem_SystemCpuLoad{instance=~\"$instance\"}[1m]) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU System Load(5m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(java_lang_OperatingSystem_SystemCpuLoad{instance=~\"$instance\"}[5m]) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemCpuLoad{instance=~\"$instance\"} * 100",
     "legendFormat": "system"
    },
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{instance=~\"$instance\"} * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_ClassLoading_LoadedClassCount{instance=~\"$instance\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Threading_ThreadCount{instance=~\"$instance\"}",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "descriptors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Heap /NonHeap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{instance=~\"$instance\"} / ignoring(area) group_left java_lang_Memory_NonHeapMemoryUsage_used{instance=~\"$instance\"} *100",
     "legendFormat": "{{area}} memory"
    }
   ]
  },
  {
   "title": "Memory Pool Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_MemoryPool_Usage_used{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Axon.ivy Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Applications",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ivy_Engine_Application_id)"
    }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ivy_Engine_Security_Manager_users"
    }
   ]
  },
  {
   "title": "Working Tasks",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ivy_Engine_Workflow_Manager_workingTasks"
    }
   ]
  },
  {
   "title": "Users / Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ivy_Engine_Security_Manager_licensedUsers",
     "legendFormat": "Users"
    },
    {
     "expr": "ivy_Engine_Security_Manager_licensedSessions",
     "legendFormat": "Sessions"
    }
   ]
  },
  {
   "title": "Connections to SystemDb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ivy_Engine_Database_Persistency_Service_openConnections",
     "legendFormat": "Open Connections"
    },
    {
     "expr": "ivy_Engine_Database_Persistency_Service_usedConnections",
     "legendFormat": "Used Connections"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 27 },
   "targets": [
    { "expr": "ivy_Engine_Application_id" }
   ]
  },
  {
   "title": "Job Executions",
   "type": "graph",
   "gridPos": { "h": 14, "w": 17, "x": 7, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ivy_Engine_Periodical_Job_executions",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Process Model",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 34 },
   "targets": [
    { "expr": "ivy_Engine_Process_Model_id" }
   ]
  },
  {
   "title": "Web Service Calls Total Execution Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "ivy_Engine_External_Web_Service_callsTotalExecutionTimeInMicroSeconds",
     "legendFormat": "{{name}} ({{application}})"
    }
   ]
  },
  {
   "title": "Job Errors",
   "type": "graph",
   "gridPos": { "h": 14, "w": 17, "x": 7, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ivy_Engine_Periodical_Job_errors",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Web Service Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ivy_Engine_External_Web_Service_calls",
     "legendFormat": "{{name}} ({{application}})"
    }
   ]
  }
 ]
}