version: '3.3'
services:
  prometheus:
    image: "prom/prometheus"
    ports:
     - "9090:9090"
    volumes:
     - "./prometheus.yml:/etc/prometheus/prometheus.yml"
     - "./alert.rules.yml:/etc/prometheus/alert.rules.yml"

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - '9093:9093'

  mysql:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  mysqld_exporter:
    image: "prom/mysqld-exporter"
    ports:
     - "9104:9104"
    environment: 
      DATA_SOURCE_NAME: "root:1234@(mysql:3306)/"
