global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
  - '/etc/prometheus/alert.rules.yml'

scrape_configs:
  - job_name: 'mysqld'
    static_configs:
    - targets: ['mysqld_exporter:9104']

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']
