global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'mysqld'
    static_configs:
    - targets: ['mysqld_exporter:9104']
  #- job_name: 'node'
  #  static_configs:
  #  - targets: ['node_exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']
