{
 "title": "Example Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ivy Mysql",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"mysql-prometheus-grafana_ivy_1\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Target Interval Length Seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds"
    }
   ]
  },
  {
   "title": "go_memstats_gc_cpu_fraction",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_gc_cpu_fraction" }
   ]
  }
 ]
}