global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'mysqld'
    static_configs:
    - targets: ['mysqld_exporter:9104']
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']